### ISSUE TITLE
question about dataset file

### ISSUE THREAD

**Issue by chen709847237** [isi-vista/BusterNet#1]
Using the google drive download link you guys provide, I download the USCISI-CMFD-Small dataset file , but when I check this file, the size of it is not 40mb but 5.4mb, and when I uncompress it, some error occur. so, I guess is there a possibility whether this file is damaged. If it's true could you guys re-upload this file?

**Comment by adamas-v** [comment]
here is the baiduNetdisk link for the full dataset:
https://blog.csdn.net/sinat_41840241/article/details/113788215
