### ISSUE TITLE
Could u tell me some details about fusion module's training？

### ISSUE THREAD

**Issue by uuhh25** [isi-vista/BusterNet#10]
If using the two branches’ output as the fusion‘s input when we train the fusion module？ Or use the two branches’ label to train the fusion module. If someone can give me some suggestion, it is so amazing！

**Comment by adamas-v** [comment]
all the training detail was put on the paper

**Comment by uuhh25** [comment]
> all the training detail was put on the paper

thank u so much!

**Comment by adamas-v** [comment]
My pleasure
But I have to say it seem not possible to re-performance the effective metric on datasets casia if the model was only trained on USCISI

**Comment by uuhh25** [comment]
> My pleasure
> But I have to say it seem not possible to re-performance the effective metric on datasets casia if the model was only trained on USCISI

Yep， I met the situation you say and I try to figure out it. May you give some suggestions to tackle it?

**Comment by uuhh25** [comment]
> If using the two branches’ output as the fusion‘s input when we train the fusion module？ Or use the two branches’ label to train the fusion module. If someone can give me some suggestion, it is so amazing！

上升
